# Generated by Django 4.2.18 on 2025-01-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descriptin',
            new_name='description',
        ),
    ]
